apiVersion: skaffold/v2beta9
kind: Config
build: 
  artifacts:
  - image: core.harbor.v2.hollysys.com/hollicube/skaffold-helm
    docker:
      dockerfile: Dockerfile
      noCache: false
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts 
      valuesFiles:
      - values.yaml