apiVersion: skaffold/v2beta9
kind: Config
build: 
  artifacts:
  - image: core.harbor.v2.hollysys.com/hollicube/skaffold-helm
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: hiaclou-io
      valuesFiles:
      - values.yaml