apiVersion: skaffold/v2beta11
kind: Config
build: 
  artifacts:
  - image: core.harbor.v2.hollysys.com/hollicube/skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
      namespace: default
      remote: false
      skipBuildDependencies: false
      #setValues:
      #  image.io.tag: v1.0
      valuesFiles:
      - values.yaml