# Default values for skaffold-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: core.harbor.v2.hollysys.com/hollicube
  pullPolicy: IfNotPresent
  io:
    name: skaffold-helm
    tag: v1.1
